/**
 * Site content manifest.
 *
 * The base ships with section components wired to this typed shape. When the
 * Bytetalent pipeline scaffolds a generated client repo, it produces a new
 * `site-content.ts` populated from the project's PRD + brand kit. The component
 * code stays the same; only the manifest values change per project.
 *
 * Strategic decision #6 in the pipeline plan — code-gen for marketing surfaces
 * becomes content-manifest generation, not JSX synthesis.
 */

export interface SiteContent {
  brand: BrandContent;
  nav: NavContent;
  hero: HeroContent;
  features: FeaturesContent;
  testimonials: TestimonialsContent;
  pricing: PricingContent;
  faq: FAQContent;
  team: TeamContent;
  cta: CTAContent;
  contact: ContactContent;
  footer: FooterContent;
  meta: MetaContent;
}

export interface BrandContent {
  name: string;
  tagline: string;
  logoUrl?: string;
}

export interface NavContent {
  links: { label: string; href: string }[];
  primaryCta: { label: string; href: string };
  signInLabel?: string;
  signInHref?: string;
}

export interface HeroContent {
  eyebrow?: string;
  title: string;
  subtitle: string;
  primaryCta: { label: string; href: string };
  secondaryCta?: { label: string; href: string };
  imageUrl?: string;
  imageAlt?: string;
}

export interface FeaturesContent {
  title: string;
  subtitle?: string;
  items: { icon?: string; title: string; description: string }[];
}

export interface TestimonialsContent {
  title?: string;
  items: { quote: string; author: string; role?: string; company?: string }[];
}

export interface PricingContent {
  title: string;
  subtitle?: string;
  tiers: {
    name: string;
    price: string;
    period?: string;
    description: string;
    features: string[];
    cta: { label: string; href: string };
    featured?: boolean;
  }[];
}

export interface FAQContent {
  title?: string;
  items: { q: string; a: string }[];
}

export interface TeamContent {
  title?: string;
  members: { name: string; role: string; imageUrl?: string; bio?: string }[];
}

export interface CTAContent {
  title: string;
  subtitle?: string;
  primaryCta: { label: string; href: string };
  secondaryCta?: { label: string; href: string };
}

export interface ContactContent {
  title: string;
  subtitle?: string;
  successMessage?: string;
}

export interface FooterContent {
  copyright: string;
  links: { label: string; href: string }[];
  socials?: { platform: "twitter" | "linkedin" | "github" | "youtube"; href: string }[];
}

export interface MetaContent {
  title: string;
  description: string;
  ogImage?: string;
}

/**
 * Default content — Bytetalent's own marketing site as the dogfooded sample.
 * Per-project content is generated by the pipeline at scaffold time.
 */
export const siteContent: SiteContent = {
  brand: {
    name: "Bytetalent",
    tagline: "Software, end-to-end, for real clients.",
  },
  nav: {
    links: [
      { label: "Features", href: "#features" },
      { label: "Pricing", href: "#pricing" },
      { label: "FAQ", href: "#faq" },
      { label: "Contact", href: "#contact" },
    ],
    primaryCta: { label: "Get Started Free", href: "#contact" },
    signInLabel: "Sign in",
    signInHref: "https://app.bytetalent.com/sign-in",
  },
  hero: {
    eyebrow: "Pipeline-grade software",
    title: "Reliably ship working software for every engagement.",
    subtitle:
      "Bytetalent's consulting pipeline turns idea capture into a deployable product — PRD, brand kit, design, architecture, code — all coherent, all generated together.",
    primaryCta: { label: "Get Started Free", href: "#contact" },
    secondaryCta: { label: "View Pricing", href: "#pricing" },
  },
  features: {
    title: "What you get",
    subtitle: "Every project produces a coherent bundle, ready to deploy.",
    items: [
      {
        title: "PRD generation",
        description:
          "Idea capture flows into a versioned PRD. Approved snapshots feed every downstream phase.",
      },
      {
        title: "Brand kit",
        description:
          "Colors, typography, and voice — derived from inspiration or imported from existing brand. Reused across projects per client.",
      },
      {
        title: "Design",
        description:
          "Pencil baseline plus brand-driven token bindings produce paired designs for every code module.",
      },
      {
        title: "Architecture review",
        description:
          "Opus-driven 8-section architecture doc, validated against the PRD before code-gen runs.",
      },
      {
        title: "Code generation",
        description:
          "Bases scaffold the foundation. Templates layer opt-in features. Agent generates only the novel modules per PRD.",
      },
      {
        title: "Deployable bundle",
        description:
          "Client repo on GitHub, deploy on Vercel/Cloudflare/Azure, infrastructure provisioned end-to-end.",
      },
    ],
  },
  testimonials: {
    items: [
      {
        quote: "Used to take weeks to scope a project; now it's a half-day end-to-end.",
        author: "Sample Consultant",
        role: "Founder",
        company: "Sample Consulting",
      },
    ],
  },
  pricing: {
    title: "Pricing",
    subtitle: "Pay for what you ship.",
    tiers: [
      {
        name: "Starter",
        price: "$0",
        period: "/forever",
        description: "Try the pipeline end-to-end.",
        features: ["1 active project", "Email support", "Bytetalent base templates"],
        cta: { label: "Get Started Free", href: "#contact" },
      },
      {
        name: "Pro",
        price: "$199",
        period: "/month",
        description: "For active consulting teams.",
        features: [
          "Unlimited projects",
          "Priority support",
          "BYOK (bring your own keys)",
          "Custom templates",
        ],
        cta: { label: "Get Started", href: "#contact" },
        featured: true,
      },
      {
        name: "Agency",
        price: "Contact",
        description: "Multi-seat consultancies.",
        features: ["Team seats", "Shared skill library", "White-label client portal"],
        cta: { label: "Contact Sales", href: "mailto:sales@bytetalent.com" },
      },
    ],
  },
  faq: {
    title: "FAQ",
    items: [
      {
        q: "What's a 'base'?",
        a: "A pre-built scaffold (Next.js webapp, Astro marketing, Expo mobile, etc.) that the pipeline reads when generating a new client repo. Real running apps, dogfooded at stable URLs.",
      },
      {
        q: "Do clients need GitHub accounts?",
        a: "Only if the project topology is 'repo lives in client's org.' Otherwise the consultancy's GitHub org owns the repo. Picked per project.",
      },
      {
        q: "What about my existing brand?",
        a: "Brand kits are client-level assets. Import an existing brand once; reuse across every project for that client.",
      },
    ],
  },
  team: {
    title: "Team",
    members: [
      {
        name: "Bytetalent",
        role: "Building the consulting pipeline",
      },
    ],
  },
  cta: {
    title: "Start your first project today.",
    subtitle: "Free for one project. No card required.",
    primaryCta: { label: "Get Started Free", href: "#contact" },
  },
  contact: {
    title: "Get in touch",
    subtitle: "Tell us about your project. We'll be in touch within 1 business day.",
    successMessage: "Thanks — we'll be in touch shortly.",
  },
  footer: {
    copyright: `© ${new Date().getFullYear()} Bytetalent. All rights reserved.`,
    links: [
      { label: "Privacy", href: "/privacy" },
      { label: "Terms", href: "/terms" },
    ],
    socials: [{ platform: "github", href: "https://github.com/bytetalent" }],
  },
  meta: {
    title: "Bytetalent — Pipeline-grade software for consultancies",
    description:
      "Bytetalent's consulting pipeline turns idea capture into a deployable product. PRD, brand kit, design, architecture, code — all coherent, all generated together.",
  },
};
